Introduce component state #13
Ayselin/kodflix pull request #1
Opened 2019-01-16 13:48 UTC by Ayselin

Introduce component state.

2019-01-16 16:10 UTC, rmallols approved these changes
Looks good Aysel - please get rid of the unnecessary empty lines before merging!

2019-01-16 16:10 UTC, rmallols commented on src/App.css
> +
Empty line :)

2019-01-16 16:10 UTC, rmallols commented on src/App.css
> +
Empty line :)

2019-01-16 16:10 UTC, rmallols commented on src/Details.js
> +
Empty line :)

2019-01-16 20:02 UTC, Ayselin commented
Will do Ricardo!

Thanks :)


________________________________
From: Ricardo Mallols <notifications@github.com>
Sent: Wednesday, January 16, 2019 4:10:59 PM
To: Ayselin/kodflix
Cc: Ayselin; Author
Subject: Re: [Ayselin/kodflix] Introduce component state #13 (#1)


@rmallols approved this pull request.

Looks good Aysel - please get rid of the unnecessary empty lines before merging!

________________________________

In src/App.css<https://github.com/Ayselin/kodflix/pull/1#discussion_r248345935>:

>  }

 .container {
   display: grid;
  grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
-  margin: 30px;
+


Empty line :)

________________________________

In src/App.css<https://github.com/Ayselin/kodflix/pull/1#discussion_r248346010>:

>    position: relative;
   overflow: hidden;

 }

 img {
   width: 100%;
+


Empty line :)

________________________________

In src/Details.js<https://github.com/Ayselin/kodflix/pull/1#discussion_r248346114>:

> +  constructor() {
+      super();
+      this.state = {
+          welcomeMessage: 'Welcome to the details page, WIP!'
+      };
+  }
+
+  componentDidMount() {
+     setTimeout(() => {
+        this.setState({
+          welcomeMessage:'The best is yet to come!!!!'
+        });
+     },3000);
+  }
+
+


Empty line :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Ayselin/kodflix/pull/1#pullrequestreview-193218606>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AinWzmAh0MBeEscAp6tTixmJV2P_u0U2ks5vD08TgaJpZM4aDGhv>.

2019-01-17 11:00 UTC, rmallols approved these changes

2019-01-22 11:46 UTC, rmallols requested changes

2019-01-22 11:46 UTC, rmallols commented on src/App.js
Unnecessary empty line here

2019-01-22 11:46 UTC, rmallols commented on src/Details/Details.css
> +
Empty line here

2019-01-22 11:46 UTC, rmallols commented on src/Details/Details.css
> +.Gallery {
Mmm...why the `Details` component starts with a `Gallery` class? it should be `Details` instead for consistency reasons!

2019-01-22 11:46 UTC, rmallols commented on src/Details/Details.js
> +
Empty line here :)

2019-01-22 11:46 UTC, rmallols commented on src/Details/Details.js
> +
Emtpy line

2019-01-22 12:04 UTC, merged